#ifndef GZJNTCMDPLUGINSHARED_GLOBAL_H
#define GZJNTCMDPLUGINSHARED_GLOBAL_H

//#include <QtCore/qglobal.h>

#if defined(GZJNTCMDPLUGIN_LIBRARY)
//#  define GZJNTCMDPLUGINSHARED_EXPORT Q_DECL_EXPORT
#  define GZJNTCMDPLUGINSHARED_EXPORT
#else
#  define GZJNTCMDPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GZJNTCMDPLUGINSHARED_GLOBAL_H
