// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JointsComm.proto

#ifndef PROTOBUF_JointsComm_2eproto__INCLUDED
#define PROTOBUF_JointsComm_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace message {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_JointsComm_2eproto();
void protobuf_AssignDesc_JointsComm_2eproto();
void protobuf_ShutdownFile_JointsComm_2eproto();

class JointsComm;

// ===================================================================

class JointsComm : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:message.JointsComm) */ {
 public:
  JointsComm();
  virtual ~JointsComm();

  JointsComm(const JointsComm& from);

  inline JointsComm& operator=(const JointsComm& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const JointsComm& default_instance();

  void Swap(JointsComm* other);

  // implements Message ----------------------------------------------

  inline JointsComm* New() const { return New(NULL); }

  JointsComm* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const JointsComm& from);
  void MergeFrom(const JointsComm& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(JointsComm* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string name = 1;
  int name_size() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name(int index) const;
  ::std::string* mutable_name(int index);
  void set_name(int index, const ::std::string& value);
  void set_name(int index, const char* value);
  void set_name(int index, const char* value, size_t size);
  ::std::string* add_name();
  void add_name(const ::std::string& value);
  void add_name(const char* value);
  void add_name(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& name() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_name();

  // repeated double position = 2;
  int position_size() const;
  void clear_position();
  static const int kPositionFieldNumber = 2;
  double position(int index) const;
  void set_position(int index, double value);
  void add_position(double value);
  const ::google::protobuf::RepeatedField< double >&
      position() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_position();

  // repeated double velocity = 3;
  int velocity_size() const;
  void clear_velocity();
  static const int kVelocityFieldNumber = 3;
  double velocity(int index) const;
  void set_velocity(int index, double value);
  void add_velocity(double value);
  const ::google::protobuf::RepeatedField< double >&
      velocity() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_velocity();

  // repeated double effort = 4;
  int effort_size() const;
  void clear_effort();
  static const int kEffortFieldNumber = 4;
  double effort(int index) const;
  void set_effort(int index, double value);
  void add_effort(double value);
  const ::google::protobuf::RepeatedField< double >&
      effort() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_effort();

  // @@protoc_insertion_point(class_scope:message.JointsComm)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> name_;
  ::google::protobuf::RepeatedField< double > position_;
  ::google::protobuf::RepeatedField< double > velocity_;
  ::google::protobuf::RepeatedField< double > effort_;
  friend void  protobuf_AddDesc_JointsComm_2eproto();
  friend void protobuf_AssignDesc_JointsComm_2eproto();
  friend void protobuf_ShutdownFile_JointsComm_2eproto();

  void InitAsDefaultInstance();
  static JointsComm* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// JointsComm

// repeated string name = 1;
inline int JointsComm::name_size() const {
  return name_.size();
}
inline void JointsComm::clear_name() {
  name_.Clear();
}
inline const ::std::string& JointsComm::name(int index) const {
  // @@protoc_insertion_point(field_get:message.JointsComm.name)
  return name_.Get(index);
}
inline ::std::string* JointsComm::mutable_name(int index) {
  // @@protoc_insertion_point(field_mutable:message.JointsComm.name)
  return name_.Mutable(index);
}
inline void JointsComm::set_name(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:message.JointsComm.name)
  name_.Mutable(index)->assign(value);
}
inline void JointsComm::set_name(int index, const char* value) {
  name_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:message.JointsComm.name)
}
inline void JointsComm::set_name(int index, const char* value, size_t size) {
  name_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:message.JointsComm.name)
}
inline ::std::string* JointsComm::add_name() {
  // @@protoc_insertion_point(field_add_mutable:message.JointsComm.name)
  return name_.Add();
}
inline void JointsComm::add_name(const ::std::string& value) {
  name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:message.JointsComm.name)
}
inline void JointsComm::add_name(const char* value) {
  name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:message.JointsComm.name)
}
inline void JointsComm::add_name(const char* value, size_t size) {
  name_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:message.JointsComm.name)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
JointsComm::name() const {
  // @@protoc_insertion_point(field_list:message.JointsComm.name)
  return name_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
JointsComm::mutable_name() {
  // @@protoc_insertion_point(field_mutable_list:message.JointsComm.name)
  return &name_;
}

// repeated double position = 2;
inline int JointsComm::position_size() const {
  return position_.size();
}
inline void JointsComm::clear_position() {
  position_.Clear();
}
inline double JointsComm::position(int index) const {
  // @@protoc_insertion_point(field_get:message.JointsComm.position)
  return position_.Get(index);
}
inline void JointsComm::set_position(int index, double value) {
  position_.Set(index, value);
  // @@protoc_insertion_point(field_set:message.JointsComm.position)
}
inline void JointsComm::add_position(double value) {
  position_.Add(value);
  // @@protoc_insertion_point(field_add:message.JointsComm.position)
}
inline const ::google::protobuf::RepeatedField< double >&
JointsComm::position() const {
  // @@protoc_insertion_point(field_list:message.JointsComm.position)
  return position_;
}
inline ::google::protobuf::RepeatedField< double >*
JointsComm::mutable_position() {
  // @@protoc_insertion_point(field_mutable_list:message.JointsComm.position)
  return &position_;
}

// repeated double velocity = 3;
inline int JointsComm::velocity_size() const {
  return velocity_.size();
}
inline void JointsComm::clear_velocity() {
  velocity_.Clear();
}
inline double JointsComm::velocity(int index) const {
  // @@protoc_insertion_point(field_get:message.JointsComm.velocity)
  return velocity_.Get(index);
}
inline void JointsComm::set_velocity(int index, double value) {
  velocity_.Set(index, value);
  // @@protoc_insertion_point(field_set:message.JointsComm.velocity)
}
inline void JointsComm::add_velocity(double value) {
  velocity_.Add(value);
  // @@protoc_insertion_point(field_add:message.JointsComm.velocity)
}
inline const ::google::protobuf::RepeatedField< double >&
JointsComm::velocity() const {
  // @@protoc_insertion_point(field_list:message.JointsComm.velocity)
  return velocity_;
}
inline ::google::protobuf::RepeatedField< double >*
JointsComm::mutable_velocity() {
  // @@protoc_insertion_point(field_mutable_list:message.JointsComm.velocity)
  return &velocity_;
}

// repeated double effort = 4;
inline int JointsComm::effort_size() const {
  return effort_.size();
}
inline void JointsComm::clear_effort() {
  effort_.Clear();
}
inline double JointsComm::effort(int index) const {
  // @@protoc_insertion_point(field_get:message.JointsComm.effort)
  return effort_.Get(index);
}
inline void JointsComm::set_effort(int index, double value) {
  effort_.Set(index, value);
  // @@protoc_insertion_point(field_set:message.JointsComm.effort)
}
inline void JointsComm::add_effort(double value) {
  effort_.Add(value);
  // @@protoc_insertion_point(field_add:message.JointsComm.effort)
}
inline const ::google::protobuf::RepeatedField< double >&
JointsComm::effort() const {
  // @@protoc_insertion_point(field_list:message.JointsComm.effort)
  return effort_;
}
inline ::google::protobuf::RepeatedField< double >*
JointsComm::mutable_effort() {
  // @@protoc_insertion_point(field_mutable_list:message.JointsComm.effort)
  return &effort_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace message

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_JointsComm_2eproto__INCLUDED
